package interfaces;

import exceptions.ProdutoException;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.clientes.Cliente;
import service.ServicoCliente;

public class Gerenciamento_clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro_clientes
     */
    Cadastro_clientes CadastroCliente = new Cadastro_clientes();
    EditarCli Editar = new EditarCli();
    VisualizarCli visu = new VisualizarCli();
    String ultimaPesquisa = null;

    public Gerenciamento_clientes() {
        initComponents();
        setResizable(false); // Bloqueia o redimensionamento lateral da tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaResultados = new javax.swing.JTable();
        Editar_cli = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        visualizarDados = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        CPF_Button = new javax.swing.JRadioButton();
        Nome_button = new javax.swing.JRadioButton();
        campo_Pesquisa = new javax.swing.JFormattedTextField();
        Label_Pesquisa = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(true);
        setTitle("Gerenciamento de Clientes");

        tabelaResultados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        tabelaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Sexo", "Endereço", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaResultados.setPreferredSize(new java.awt.Dimension(375, 16));
        jScrollPane2.setViewportView(tabelaResultados);
        if (tabelaResultados.getColumnModel().getColumnCount() > 0) {
            tabelaResultados.getColumnModel().getColumn(0).setMinWidth(0);
            tabelaResultados.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabelaResultados.getColumnModel().getColumn(0).setMaxWidth(0);
            tabelaResultados.getColumnModel().getColumn(1).setResizable(false);
            tabelaResultados.getColumnModel().getColumn(2).setResizable(false);
            tabelaResultados.getColumnModel().getColumn(3).setResizable(false);
            tabelaResultados.getColumnModel().getColumn(4).setResizable(false);
            tabelaResultados.getColumnModel().getColumn(5).setResizable(false);
        }

        Editar_cli.setText("Editar ");
        Editar_cli.setToolTipText("Edita o cliente selecionado");
        Editar_cli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));
        Editar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_cliActionPerformed(evt);
            }
        });

        jButton4.setText("Cadastrar Cliente");
        jButton4.setToolTipText("Cadastra novo cliente");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Sair");
        jButton5.setToolTipText("Fecha esta janela");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Excluir");
        jButton6.setToolTipText("Deleta o cliente selecionado");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        visualizarDados.setText("Visualizar ");
        visualizarDados.setToolTipText("Visualiza dados do cliente selecionado");
        visualizarDados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));
        visualizarDados.setName(""); // NOI18N
        visualizarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarDadosActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setForeground(new java.awt.Color(204, 0, 0));

        jPanel7.setBackground(new java.awt.Color(102, 0, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Filtro de pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        CPF_Button.setBackground(new java.awt.Color(102, 0, 102));
        buttonGroup1.add(CPF_Button);
        CPF_Button.setForeground(new java.awt.Color(255, 255, 255));
        CPF_Button.setText("CPF");
        CPF_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPF_ButtonMouseClicked(evt);
            }
        });

        Nome_button.setBackground(new java.awt.Color(102, 0, 102));
        buttonGroup1.add(Nome_button);
        Nome_button.setForeground(new java.awt.Color(255, 255, 255));
        Nome_button.setText("Nome do Cliente");
        Nome_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nome_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CPF_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF_Button)
                    .addComponent(Nome_button))
                .addGap(12, 12, 12))
        );

        campo_Pesquisa.setText("Campo de pesquisa...");
        campo_Pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_PesquisaMouseClicked(evt);
            }
        });

        Label_Pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Img/search_1.png"))); // NOI18N
        Label_Pesquisa.setToolTipText("Clique para pesquisar");
        Label_Pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_PesquisaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campo_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Pesquisa)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Pesquisa)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(visualizarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Editar_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visualizarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean refreshList() throws ProdutoException, Exception {
        if (Nome_button.isSelected() || !Nome_button.isSelected() ) {//pesquisa através do parametro NOME
            List<Cliente> resultado = ServicoCliente.
                    procurarCliente(ultimaPesquisa);
            DefaultTableModel model = (DefaultTableModel) tabelaResultados.getModel();
            model.setRowCount(0);
            if (resultado == null || resultado.size() <= 0) {
                return false;
            }
            for (int i = 0; i < resultado.size(); i++) {
                Cliente cli = resultado.get(i);
                if (cli != null) {
                    Object[] row = new Object[6];
                    row[0] = cli.getId();
                    row[1] = cli.getNome();
                    row[2] = cli.getCPF();
                    row[3] = cli.getGenero();
                    row[4] = cli.getEndereco();
                    row[5] = cli.getTelefone_casa();
                    model.addRow(row);
                }
            }
            return true;
        } else if (CPF_Button.isSelected()) {//pesquisa através do parametro CPF
            List<Cliente> resultado = ServicoCliente.
                    procurarClienteCPF(ultimaPesquisa);
            DefaultTableModel model = (DefaultTableModel) tabelaResultados.getModel();
            model.setRowCount(0);
            if (resultado == null || resultado.size() <= 0) {
                return false;
            }
            for (int i = 0; i < resultado.size(); i++) {
                Cliente cli = resultado.get(i);
                if (cli != null) {
                    Object[] row = new Object[6];
                    row[0] = cli.getId();
                    row[1] = cli.getNome();
                    row[2] = cli.getCPF();
                    row[3] = cli.getGenero();
                    row[4] = cli.getEndereco();
                    row[5] = cli.getTelefone_casa();
                    model.addRow(row);
                }
            }
            return true;
        }
        return true;
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (CadastroCliente == null || CadastroCliente.isDisplayable()) {
            CadastroCliente = new Cadastro_clientes();
        }
        this.getParent().add(CadastroCliente);
        this.openFrameInCenter(CadastroCliente);
        CadastroCliente.toFront();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (tabelaResultados.getSelectedRow() >= 0) {
            final int row = tabelaResultados.getSelectedRow();
            String nome = (String) tabelaResultados.getValueAt(row, 1);
            int resposta = JOptionPane.showConfirmDialog(rootPane,
                    "Excluir o Cliente \"" + nome + "\"?",
                    "Confirmar exclusão", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    Integer id = (Integer) tabelaResultados.getValueAt(row, 0);
                    ServicoCliente.excluirCliente(id);
                    this.refreshList();
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                            "Falha na Exclusão", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Você não selecionou ninguém.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Label_PesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_PesquisaMouseClicked
        if (evt.getClickCount() == 1) {

            boolean resultSearch = false;
            ultimaPesquisa = campo_Pesquisa.getText();

            try {
                resultSearch = refreshList();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                        "Falha ao obter lista", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!resultSearch) {
                JOptionPane.showMessageDialog(rootPane, "A pesquisa não retornou resultados ",
                        "Sem resultados", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Label_PesquisaMouseClicked

    private void visualizarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarDadosActionPerformed
        try {
            final int row = tabelaResultados.getSelectedRow();
            if (row >= 0) {
                Integer id = (Integer) tabelaResultados.getValueAt(row, 0);

                Cliente cliente = ServicoCliente.obterCliente(id);

                visu.dispose();
                visu = new VisualizarCli();
                visu.setCliente(cliente);
                visu.setTitle(cliente.getNome() + " ");
                this.getParent().add(visu);
                this.openFrameInCenter(visu);
                visu.toFront();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não selecionou ninguém.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Não é possível "
                    + "exibir os detalhes deste cliente.",
                    "Erro ao abrir detalhe", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_visualizarDadosActionPerformed

    private void Editar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_cliActionPerformed
        try {
            final int row = tabelaResultados.getSelectedRow();
            if (row >= 0) {
                Integer id = (Integer) tabelaResultados.getValueAt(row, 0);

                Cliente cliente = ServicoCliente.obterCliente(id);

                Editar.dispose();
                Editar = new EditarCli();
                Editar.setCliente(cliente);
                Editar.setTitle(cliente.getNome() + " ");
                this.getParent().add(Editar);
                this.openFrameInCenter(Editar);
                Editar.toFront();
                this.refreshList();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não selecionou ninguém.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Não é possível "
                    + "exibir os detalhes deste cliente.",
                    "Erro ao abrir detalhe", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Editar_cliActionPerformed

    private void Nome_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nome_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nome_buttonActionPerformed

    private void CPF_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPF_ButtonMouseClicked

    }//GEN-LAST:event_CPF_ButtonMouseClicked

    private void campo_PesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_PesquisaMouseClicked
         if (CPF_Button.isSelected()) {
            try {
                campo_Pesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
        }else if (!CPF_Button.isSelected()){
         campo_Pesquisa.setText("");
         }
    }//GEN-LAST:event_campo_PesquisaMouseClicked
    public void openFrameInCenter(JInternalFrame jif) {
        Dimension desktopSize = this.getParent().getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CPF_Button;
    private javax.swing.JButton Editar_cli;
    private javax.swing.JLabel Label_Pesquisa;
    private javax.swing.JRadioButton Nome_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JFormattedTextField campo_Pesquisa;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaResultados;
    private javax.swing.JButton visualizarDados;
    // End of variables declaration//GEN-END:variables
}
